### ISSUE TITLE
Article about Isaiah and OpenZiti BrowZer

### ISSUE THREAD

**Issue by rentallect** [will-moss/isaiah#13]
@will-moss I just wanted to mention that I published an article involving Isaiah on our OpenZiti tech blog, hoping to spread the love.

https://blog.openziti.io/effortless-docker-management-with-private-web-access

Thanks for creating Isaiah.

**Comment by will-moss** [comment]
Hey!

Thanks a lot, much appreciated. It definitely means a lot to me.

Is there anything that I can do in return? Or should I close the issue?

Let me know, that's a first for me.

Thanks again

**Comment by rentallect** [comment]
We always appreciate getting GH stars on https://github.com/openziti/ziti :)

If you have time to drop a tweet, or a Reddit post about my article, that would be fantastic as well.

If you do, let me know where.

Meanwhile, yes, you can close this issue (since it was just a way for me to reach out to you)
