### ISSUE TITLE
[Bug] Image name does not display correctly in some cases

### ISSUE THREAD

**Issue by shizunge** [will-moss/isaiah#15]
The image name is `<none>`, see the screenshot
![image](https://github.com/user-attachments/assets/5caeaa72-32ff-4b72-a5e4-8370a1993dd8)

Possible cause (just my guess)
The `RepoTags` of the image is empty
`sudo docker image inspect 3ed07fe68878`

```
[
    {
        "Id": "sha256:3ed07fe688788bfd12aadce5b7f0b781a3b1b072ce04f4292b97d9966cf17c27",
        "RepoTags": [],
        "RepoDigests": [
            "lscr.io/linuxserver/mariadb@sha256:9f129e37e591a09647c33169ce6e4a7412309de45f0f9420d82b4f9c6ecdec2c"
        ],
        "Parent": "",
        "Comment": "buildkit.dockerfile.v0",
        "Created": "2024-09-24T07:43:46.835022657Z",
        "DockerVersion": "",
        "Author": "",
......
```

If that is the cause, Can we get the image name from `RepoDigests` when `RepoTags` is empty string.

**Comment by will-moss** [comment]
Thanks for the issue along with the idea of using RepoDigests.

I have just published a new release that includes a fallback to RepoDigests when RepoTags is empty.

Hoping that it works better on your end now?

**Comment by shizunge** [comment]
You fixed the problem much quicker than I expected. Thanks.

I will report back when I get time to try the new version.

**Comment by shizunge** [comment]
Seems fixed
