### ISSUE TITLE
[feature] View content of volumes inside isaiah container.

### ISSUE THREAD

**Issue by shizunge** [will-moss/isaiah#16]
I deploy *isaiah* via docker.
When I try to **browser volume in shell** I get the following error and cannot proceed.

![image](https://github.com/user-attachments/assets/010fdc07-6978-42e7-89fd-912bce64bb8c)

I think if we have mapped the docker volumes from the host to the container of isaish (e.g. `/var/lib/docker/volumes:/var/lib/docker/volumes`), we should be allowed to view the content of the voluems.

**Comment by shizunge** [comment]
I learnt that the isaiah image does not contain a shell.

If I build the image based on `alpinelinux/docker-cli:latest` and do not set `DOCKER_RUNNING`, I can view the volume.

**Comment by will-moss** [comment]
Alright.

I was busy lately, but I finally managed to tweak the code, run tests, and ensure that everything works.

I have just published a new release, and you should now be able to browse your volumes even when Isaiah is deployed in a Docker container, provided that you have previously added a mount that is identical to the one you've provided in your first comment (and that's also indicated in the error popup if anyone needs it!).

Hoping that it works better now, and thanks again for opening that issue.

**Comment by shizunge** [comment]
It does not work on the node where "Agent" is running. (Multi-node mode). The agent hangs somehow.

**Comment by will-moss** [comment]
Thanks a lot for your feedback.

I did not test the feature in multi-node mode, it's my bad, my apologies.

I have just fixed the code to accomodate multi-node mode, and it should work now (or at least, it works on my end).

You can pull the latest image.

Sorry again, and looking forward to reading from you!

**Comment by shizunge** [comment]
Thank you!
