### ISSUE TITLE
Isaiah hangs when trying to view stats for "created" container

### ISSUE THREAD

**Issue by vutsalsinghal** [will-moss/isaiah#3]
Small scope of improvement - 

1. Isaiah hangs when trying to view stats for container which has "created" state. I know there won't be any stats, but would be nice if it doesnt hang and displays some message like - "Container isn't running."
2. Copy/paste for other tabs like "Stats", "Env", "Config", etc doesnt work. I think similar to pausing render loop on mouse hover for logs tab is needed for other tabs too

**Comment by will-moss** [comment]
Thank you for opening the issue and explaining the problems occurring!

I have just published a release that should address both problems:
- Now the mouse hover on the Inspector will block the render-loop, not only for the Logs tab, but for all tabs (Env, Stats, etc.).
- Now, trying to retrieve stats from a "Created" container won't trigger a "infinite hanging paralysis" on the client anymore. It will mention "Container isn't running" instead.

I hope that works for you!

**Comment by vutsalsinghal** [comment]
Both issues are resolved! Thank you 🙏🏼 ❤️
